#!/bin/sh
echo "running test '$1'"
rlwrap guile \
	-l push-pop-boxes.scm \
	-l peg-result.scm \
	-l peg.scm \
	-l rackunit.scm \
	-l s-exp.scm \
	-l peg-in-peg.scm \
	-l peg-to-scheme.scm \
	-l guile-heredoc.scm \
	"$1" && echo ok

